name: compute-scaling
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - transformers=4.30.2
  - datasets=2.13.1
  - accelerate=0.20.3
  - deepspeed=0.9.5
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - tqdm=4.65.0
  - tensorboard=2.13.0
  - pip
  - pip:
    - wandb