# Configuration for R-UniMP on Citation Network V1
data_dir: "dataset"
samples: "15-10"
seed: 42
num_workers: 0  # macOS-safe: avoid multiprocessing
batch_size: 32

# Model parameters
model:
    name: "hetero_unimp"
    input_size: 768
    num_class: 100  # Reduced from 12609 to make training more manageable
    num_layers: 2
    feat_drop: 0.0
    attn_drop: 0.0
    num_heads: 4
    hidden_size: 512
    activation: False
    drop: 0.5
    edge_type: 3  # citation, author->paper, paper->author

# M2V parameters
m2v_dim: 512

# Training parameters
output_path: "./output/citationnetwork_runimp"
epochs: 10  # Reduced for testing
eval_step: 2
eval_per_steps: 2
eval_max_steps: 10  # Reduced for testing
max_steps: 20  # Reduced for testing

# Optimizer parameters
warmup_proportion: -1
weight_decay: 0.0001
lr: 0.001
clip: -1
use_lr_decay: True

# Runtime (optional)
device: cpu
pin_memory: false
persistent_workers: false

# Test parameters
test_name: "test"
